=== nainaiguang/Treeses/SYSTEM/CONFIG/Tabletype_config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="tables">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="table" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="table_name" type="xs:string"/>
							<xs:element name="owner" type="xs:string"/>
							<xs:element name="jurisdiction" type="xs:string"/>
							<xs:element name="address" type="xs:string"/>
							<xs:element name="alias" type="xs:string"/>
							<xs:element name="columns">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="column" minOccurs="0" maxOccurs="unbounded">
										<xs:complexType>
										<xs:attribute name="name" type="xs:string"/>
										<xs:attribute name="type" type="xs:string"/>
										</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== nainaiguang/Treeses/SYSTEM/DICTIONARY/Tabletype.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><tables xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../CONFIG/Tabletype_config.xsd">
	<table>
		<table_name>asdwqa</table_name>
		<owner>drfwq3er</owner>
		<jurisdiction>READ_WRITE</jurisdiction>
		<address>sss</address>
		<alias>none</alias>
		<columns>
			<column name="sss" type="sssd"/>
		<column name="dawedawdxa" type="dawedawdxa"/><column name="sdawecsdfsa" type="sdawecsdfsa"/><column name="awsdfsa" type="awsdfsa"/><column name="aa" type="aa"/></columns>
	</table>
<table><table_name>testalter_tbl</table_name><owner>SYSTEM</owner><jurisdiction>READ_WRITE</jurisdiction><address>SYSTEM\DATA\USER\SYSTEM\TABLE\testalter_tbl.txt</address><alias>none</alias><columns><column name="i" type="INT"/><column name="c" type="CHAR"/></columns></table><table><table_name>testalter_tblS</table_name><owner>SYSTEM</owner><jurisdiction>READ_WRITE</jurisdiction><address>SYSTEM\DATA\USER\SYSTEM\TABLE\testalter_tblS.txt</address><alias>none</alias><columns><column name="i" type="CHAR"/><column name="c" type="CHAR"/></columns></table><table><table_name>nng</table_name><owner>SYSTEM</owner><jurisdiction>READ_WRITE</jurisdiction><address>SYSTEM\DATA\USER\SYSTEM\TABLE\nng.txt</address><alias>none</alias><columns><column name="id" type="INT"/><column name="name" type="VARCHAR"/></columns></table></tables>
